//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成�?
//
//     手动更改此文件可能导致应用程序出现意外的行为�?
//     如果重新生成代码，将覆盖对此文件的手动更改�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.MusicScore = new HashSet<MusicScore>();
            this.MusicScoreCollection = new HashSet<MusicScoreCollection>();
            this.MusicScoreComment = new HashSet<MusicScoreComment>();
            this.Post = new HashSet<Post>();
            this.PostCollection = new HashSet<PostCollection>();
            this.PostComment = new HashSet<PostComment>();
            this.Video = new HashSet<Video>();
            this.VideoCollection = new HashSet<VideoCollection>();
            this.VideoComment = new HashSet<VideoComment>();
        }
    
        public int User_id { get; set; }
        public string User_name { get; set; }
        public string User_password { get; set; }
        public string User_email { get; set; }
        public string User_img { get; set; }
        public System.DateTime User_addtime { get; set; }
        public string User_sex { get; set; }
        public string User_birthday { get; set; }
        public string User_sign { get; set; }
        public string User_addr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScore> MusicScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreCollection> MusicScoreCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreComment> MusicScoreComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostCollection> PostCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCollection> VideoCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComment { get; set; }
    }
}
