//------------------------------------------------------------------------------
// <auto-generated>
//     姝や唬鐮佸凡浠庢ā鏉跨敓鎴愩�?
//
//     鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳藉鑷村簲鐢ㄧ▼搴忓嚭鐜版剰澶栫殑琛屼负銆?
//     濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽皢瑕嗙洊瀵规鏂囦欢鐨勬墜鍔ㄦ洿鏀广�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guitar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.MusicScore = new HashSet<MusicScore>();
            this.MusicScoreCollection = new HashSet<MusicScoreCollection>();
            this.MusicScoreComment = new HashSet<MusicScoreComment>();
            this.MusicScoreReply = new HashSet<MusicScoreReply>();
            this.Post = new HashSet<Post>();
            this.PostCollection = new HashSet<PostCollection>();
            this.PostComment = new HashSet<PostComment>();
            this.PostReply = new HashSet<PostReply>();
            this.Video = new HashSet<Video>();
            this.VideoCollection = new HashSet<VideoCollection>();
            this.VideoComment = new HashSet<VideoComment>();
            this.VideoReply = new HashSet<VideoReply>();
        }

        public int User_id { get; set; }
        [Required(ErrorMessage = "用户名不为空")]
        [MaxLength(8, ErrorMessage = "昵称不超过8个字符!")]
        public string User_name { get; set; }
        [Required]
        [Display(Name = "密码")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "密码必须至少包含6个字符!")]
        [DataType(DataType.Password)]
        public string User_password { get; set; }

        //[Display(Name = "确认密码")]
        //[Required(ErrorMessage = "确认密码必填")]
        //[DataType(DataType.Password)]
        //[Compare("User_password", ErrorMessage = "密码和确认密码不正确")]
        //public string ConfirmPassword { get; set; }
        //[Required]
        [Display(Name = "邮箱")]
        [Required(ErrorMessage = "邮箱必填")]
        [RegularExpression(@"^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$", ErrorMessage = "请输入正确的Email格式\n示例：abc@123.com")]
        //[EmailAddress]
        //[Display(Name = "电子邮件")]
        //[DataType(DataType.EmailAddress, ErrorMessage = "邮箱地址格式不正确!")]
        public string User_email { get; set; }
        public string User_img { get; set; }
        public System.DateTime User_addtime { get; set; }
        public string User_sex { get; set; }
        public string User_birthday { get; set; }
        public string User_sign { get; set; }
        public string User_addr { get; set; }
        public bool RememberMe { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScore> MusicScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreCollection> MusicScoreCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreComment> MusicScoreComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicScoreReply> MusicScoreReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostCollection> PostCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostReply> PostReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCollection> VideoCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoReply> VideoReply { get; set; }
    }
}
